package com.belahza.app;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public final class EmergencyData {
    public static final String EXTRA_KEY = "emergency_key";
    public static final class Emergency {
        public final String key, title, arabic, category, oneLine, animationType, callTarget;
        public final int accent, videoRes;
        public final List<String> steps, donts, redFlags;
        Emergency(String key, String title, String arabic, String category, String oneLine, int accent, String animationType, String callTarget, int videoRes, List<String> steps, List<String> donts, List<String> redFlags) { this.key=key; this.title=title; this.arabic=arabic; this.category=category; this.oneLine=oneLine; this.accent=accent; this.animationType=animationType; this.callTarget=callTarget; this.videoRes=videoRes; this.steps=steps; this.donts=donts; this.redFlags=redFlags; }
    }
    public static final class NumberItem { public final String title, subtitle, number; public final int accent; public NumberItem(String title,String subtitle,String number,int accent){this.title=title;this.subtitle=subtitle;this.number=number;this.accent=accent;} }
    public static List<NumberItem> numbers(){return Arrays.asList(new NumberItem("Lebanese Red Cross","Ambulance / medical emergency","140",Ui.RED),new NumberItem("Internal Security Forces","Police / immediate danger","112",Ui.NAVY),new NumberItem("Civil Defense","Rescue / fire / floods","125",0xFFFF7A00),new NumberItem("Fire Brigade","Fire response","175",0xFFD1121B),new NumberItem("General Security","Border / residency / official security","1717",0xFF274C77),new NumberItem("Lebanese Army","Security emergency","1701",0xFF3E5F44),new NumberItem("Ministry of Public Health","Health services hotline","1787",0xFF168AAD),new NumberItem("Road Conditions","Traffic / roads","1744",0xFF5A4FCF));}
    public static Emergency get(String key){for(Emergency e:emergencies())if(e.key.equals(key))return e;return emergencies().get(0);}    
    public static List<Emergency> emergencies(){ArrayList<Emergency> e=new ArrayList<>();
        e.add(new Emergency("cardiac","Cardiac Arrest / CPR","توقف القلب","Life threat","Unresponsive and not breathing normally. Call help and start compressions.",Ui.RED,"cardiac","140",R.raw.cpr_guide,Arrays.asList("Check safety and responsiveness.","Call 140 or 112. Ask for an AED.","If not breathing normally, place hands in the center of the chest.","Push hard and fast with straight arms and shoulders above hands.","Use AED as soon as it arrives and follow prompts.","Continue until professionals arrive or normal breathing returns."),Arrays.asList("Do not delay calling emergency services.","Do not stop compressions for long pauses.","Do not lean on the chest between compressions."),Arrays.asList("Unresponsive","No normal breathing","Collapse","Blue or gray skin")));
        e.add(new Emergency("choking","Choking / Heimlich","اختناق","Airway","Cannot speak, cough, breathe, cry, or laugh forcefully.",0xFFFF7A00,"choking","140",R.raw.choking_guide,Arrays.asList("Ask: Are you choking? Encourage strong coughing if possible.","If they cannot breathe or speak, call for help.","Give 5 firm back blows between shoulder blades.","Give 5 abdominal thrusts above the navel and below the ribs.","Repeat 5 and 5 until object clears or person becomes unresponsive.","If unresponsive, lower carefully and start CPR."),Arrays.asList("Do not sweep fingers blindly in the mouth.","Do not give water to someone who cannot breathe.","Do not use adult abdominal thrusts on infants."),Arrays.asList("Silent cough","Hands at throat","Cannot speak","Blue lips")));
        e.add(new Emergency("bleeding","Severe Bleeding","نزيف قوي","Trauma","Blood spurting, pooling, or not stopping. Apply firm pressure now.",0xFFB00020,"bleeding","140",R.raw.bleeding_guide,Arrays.asList("Call 140/112 or ask someone nearby to call.","Expose enough to find the bleeding source.","Apply firm, steady pressure with clean cloth or clothing.","Add more cloth if soaked; do not remove the first layer.","Use a tourniquet only if trained and bleeding is life-threatening on a limb.","Keep the person warm and still."),Arrays.asList("Do not remove embedded objects.","Do not repeatedly check the wound if pressure is working.","Do not give food or drink."),Arrays.asList("Spurting blood","Large pool of blood","Shock signs","Major injury")));
        e.add(new Emergency("burns","Burns","حروق","Injury","Cool the burn. Cover loosely. Call for serious burns.",0xFFFF5D00,"burns","140",R.raw.burns_guide,Arrays.asList("Move away from heat, flame, chemical, or electricity.","Cool under cool running water when possible.","Remove jewelry or tight items before swelling.","Cover with clean non-stick dressing or cloth.","Call for large, deep, face/hand/genital burns, smoke inhalation, or children."),Arrays.asList("Do not apply ice directly.","Do not break blisters.","Do not apply butter, oils, toothpaste, or powders."),Arrays.asList("Large burn","Face or airway burn","Chemical/electrical burn","Trouble breathing")));
        e.add(new Emergency("stroke","Stroke Signs","جلطة دماغية","Neurologic","Face droop, arm weakness, speech trouble: time matters.",0xFF6A4C93,"stroke","140",R.raw.stroke_guide,Arrays.asList("Use FAST: Face, Arms, Speech, Time.","Call 140/112 immediately and note symptom start time.","Keep them resting with head slightly raised if comfortable.","Do not give food, drink, or medication unless instructed.","Monitor breathing and prepare for CPR if needed."),Arrays.asList("Do not wait to see if symptoms pass.","Do not drive if emergency response is available.","Do not give aspirin unless advised by professionals."),Arrays.asList("Face droop","Arm weakness","Slurred speech","Sudden severe headache")));
        e.add(new Emergency("seizure","Seizure","نوبة تشنج","Neurologic","Protect from injury. Time it. Do not restrain.",0xFF4D96FF,"seizure","140",R.raw.seizure_guide,Arrays.asList("Move hazards away and protect the head.","Start timing the seizure.","Do not restrain and do not put anything in the mouth.","When shaking stops, check breathing and roll to side if safe.","Call help if over 5 minutes, repeated, injured, pregnant, diabetic, or first seizure."),Arrays.asList("Do not hold them down.","Do not put objects in the mouth.","Do not give food or drink until fully awake."),Arrays.asList("Over 5 minutes","Repeated seizures","Injury","Pregnancy or diabetes")));
        e.add(new Emergency("fire","Fire / Smoke","حريق / دخان","Rescue","Get low, get out, call help. Smoke kills fast.",0xFFE63946,"fire","125",R.raw.fire_guide,Arrays.asList("Alert people nearby and leave immediately.","Stay low under smoke and cover mouth/nose if possible.","Close doors behind you.","Call 125, 175, or 112 once safe.","If trapped, seal gaps, signal from window, and share location."),Arrays.asList("Do not use elevators.","Do not re-enter for belongings.","Do not open hot doors."),Arrays.asList("Thick smoke","Trapped people","Gas smell","Breathing difficulty")));
        e.add(new Emergency("car","Car Accident","حادث سير","Trauma","Secure scene, call help, do not move injured people unless immediate danger.",0xFF264653,"car","112",R.raw.crash_guide,Arrays.asList("Move to safety and turn on hazard lights if possible.","Call 112/140 and give exact location and number injured.","Do not move possible spine injury unless fire or immediate danger.","Control bleeding with firm pressure.","Keep injured people warm and still."),Arrays.asList("Do not stand in traffic.","Do not remove helmets unless airway is blocked and you are trained.","Do not give food or drink."),Arrays.asList("Unconscious","Heavy bleeding","Trapped person","Fire/fuel leak")));
        e.add(new Emergency("electric","Electric Shock","صعقة كهربائية","Rescue","Cut power first. Do not touch until safe.",0xFFFFC300,"electric","125",R.raw.electric_guide,Arrays.asList("Do not touch while connected to electricity.","Turn off power or unplug if safe.","Call for serious shock, burns, or loss of consciousness.","Once safe, check breathing and start CPR if needed.","Cool burns and cover loosely."),Arrays.asList("Do not use metal objects to move wires.","Do not touch downed power lines.","Do not ignore chest pain after shock."),Arrays.asList("Unresponsive","Burns","High voltage","Chest pain")));
        e.add(new Emergency("breathing","Breathing Problem","صعوبة تنفس","Medical","Sit upright, use prescribed inhaler, call if severe.",0xFF00A8E8,"breathing","140",R.raw.breathing_guide,Arrays.asList("Help them sit upright and loosen tight clothing.","Ask if they have prescribed inhaler/medicine and help use it.","Keep area calm and ventilated.","Call 140/112 if severe, blue lips, chest pain, or no improvement.","Prepare for CPR if breathing stops."),Arrays.asList("Do not force them to lie flat.","Do not give someone else’s medication.","Do not delay calling if getting worse."),Arrays.asList("Blue lips","Cannot speak full sentences","Chest pain","Severe allergy")));
        e.add(new Emergency("unconscious","Unconscious Person","فاقد الوعي","Life threat","Check breathing. Recovery position if breathing; CPR if not.",0xFF2A9D8F,"unconscious","140",R.raw.unconscious_guide,Arrays.asList("Check safety and try to wake with voice and shoulder tap.","Call 140/112 immediately.","Open airway and check normal breathing.","If breathing normally, place on side if safe and monitor.","If not breathing normally, start CPR and ask for AED."),Arrays.asList("Do not give food, drink, or medication.","Do not shake violently.","Do not leave them alone."),Arrays.asList("No normal breathing","Head injury","Vomiting","Poisoning suspected")));
        e.add(new Emergency("panic","Panic / Distress","هلع / توتر","Mental health","Breathe, ground, stay with them. Call if danger or self-harm risk.",0xFF00B4D8,"panic","140",R.raw.panic_guide,Arrays.asList("Move to a quieter safer place if possible.","Speak calmly and stay with them.","Guide breathing: inhale 4 seconds, exhale 6 seconds.","Use grounding: 5 things seen, 4 felt, 3 heard.","Call emergency help if chest pain, fainting, self-harm risk, or violence."),Arrays.asList("Do not shame or argue.","Do not crowd them.","Do not ignore self-harm threats."),Arrays.asList("Chest pain","Fainting","Self-harm risk","Unsafe environment")));
        e.add(new Emergency("allergy","Severe Allergy","حساسية قوية","Medical","Swelling, wheeze, rash, or collapse can be anaphylaxis.",0xFF9B5DE5,"allergy","140",R.raw.allergic_guide,Arrays.asList("Call 140/112 if breathing, swelling, faintness, or rapid worsening.","Help use prescribed epinephrine auto-injector if available.","Let them sit upright if breathing is easier or lie down if faint.","Monitor breathing and prepare for CPR if unresponsive.","A second dose may be needed if prescribed and symptoms continue."),Arrays.asList("Do not make them walk around.","Do not delay prescribed epinephrine.","Do not give oral medicine if they cannot swallow safely."),Arrays.asList("Trouble breathing","Face/tongue swelling","Fainting","Rapid widespread rash")));
        e.add(new Emergency("poison","Poisoning / Overdose","تسمم","Medical","Identify substance. Call emergency help. Do not induce vomiting unless told.",0xFF495057,"poison","140",R.raw.poisoning_guide,Arrays.asList("Call 140/112 and say what was taken, how much, and when.","Keep container, label, pills, or chemical for responders.","If unconscious but breathing, place on side and monitor.","If not breathing normally, start CPR.","For chemicals on skin, remove contaminated clothing and rinse if safe."),Arrays.asList("Do not induce vomiting unless instructed.","Do not give food, drink, or alcohol.","Do not wait for symptoms after dangerous exposure."),Arrays.asList("Unconscious","Seizure","Breathing problem","Intentional overdose")));
        e.add(new Emergency("explosion","Explosion / Collapse","انفجار / انهيار","Disaster","Move from danger, share location, control bleeding, signal if trapped.",0xFF6C584C,"explosion","125",R.raw.earthquake_guide,Arrays.asList("Move away from unstable structures, glass, smoke, and secondary hazards.","Call 125/112/140 and share exact location.","Control life-threatening bleeding with pressure.","If trapped, cover mouth/nose, tap or signal, conserve battery.","Do not move heavy debris unless safe and necessary."),Arrays.asList("Do not rush back into damaged buildings.","Do not light matches near gas smell.","Do not move severely injured people unless danger is immediate."),Arrays.asList("Trapped person","Heavy bleeding","Smoke inhalation","Unstable building")));
        e.add(new Emergency("drowning","Drowning","غرق","Water rescue","Remove from water safely, check breathing, start CPR if needed.",0xFF0077B6,"drowning","140",R.raw.drowning_guide,Arrays.asList("Do not enter dangerous water unless trained; reach or throw flotation first.","Call 140/112 as soon as possible.","Once out, check responsiveness and breathing.","If not breathing normally, start CPR and use AED when available.","Keep warm and monitor even if they seem better."),Arrays.asList("Do not become a second victim.","Do not delay CPR to drain water.","Do not ignore coughing or breathing trouble after rescue."),Arrays.asList("Not breathing","Blue/gray color","Confusion","Persistent cough")));
        return e; }
}
